name: "Build and deploy Github pages"

on:
  push:
    branches:
      - master
    paths:
      - "manual/**"

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest

    steps:

      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: "Set up Python"
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: "Install Python dependencies"
        run: |
          pip3 install -r requirements.txt

      - name: "Build Sphinx Doc"
        run: |
          make html

      - name: "Deploy Github Pages"
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build/html/
